spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: create
  application:
    name: mcp-client
  datasource:
    platform: h2
    url: jdbc:h2:file:~/test;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password:
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        memory:
          repository:
            jdbc:
              initialize-schema: always
        options:
          model: llama-3.1-8b-instant
          temperature: 0.7
    google:
      genai.api-key:  ${GEN_API_KEY}
    mcp:
      client:
        logging:
          level: debug
        type: ASYNC
        name: my-mcp-client
        initialized: true
        streamable-http:
          connections:
            server1:
              url: http://localhost:8081
              endpoint: /mcp
vaadin:
  launch-browser: true
  exclude-urls:
    - /h2-console


logging:
  level:
    io:
      modelcontextprotocol: TRACE
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG